Repository cancervariants/metakb, pull requests merged in 2024-07, with the labels that each got.

#370 refactor!: remove `extract_harvester` from `transform` method
  src/metakb/cli.py
  src/metakb/harvesters/base.py
  src/metakb/transform/base.py
  src/metakb/transform/civic.py
  src/metakb/transform/moa.py
  tests/unit/transform/test_civic_transform_therapeutic.py
  tests/unit/transform/test_moa_transform.py
Labels: priority:low, technical debt

#371 refactor!: rename `Transform` instance variables
  src/metakb/database.py
  src/metakb/transform/base.py
  src/metakb/transform/civic.py
  src/metakb/transform/moa.py
Labels: priority:low, technical debt

#376 feat!: initialize query handler with graph, not graph credentials
  src/metakb/query.py
Labels: priority:low

#377 feat!: refactor graph DB code, streamline unneeded query transaction usage
  docs/source/reference/api/metakb.database.rst
  docs/source/reference/api/metakb.load_data.rst
  docs/source/reference/index.rst
  src/metakb/cli.py
  src/metakb/database.py
  src/metakb/load_data.py
  src/metakb/query.py
  tests/unit/database/test_database.py
Labels: priority:medium

#374 feat!: replace instance var lists with pydantic model
  src/metakb/transform/base.py
  src/metakb/transform/civic.py
  src/metakb/transform/moa.py
  tests/conftest.py
Labels: priority:medium, technical debt

#378 fix: catch TokenRetrievalError in ViccNormalizers + update log levels
  src/metakb/normalizers.py
Labels: bug, priority:low

#382 feat: update pre-commit version + add more hooks
  .pre-commit-config.yaml
  Pipfile
  pyproject.toml
Labels: enhancement, priority:low

#381 feat!: use setuptools-scm, capture version at package root
  docs/source/conf.py
  pyproject.toml
  src/metakb/__init__.py
  src/metakb/main.py
  src/metakb/schemas/api.py
  src/metakb/version.py
Labels: enhancement, priority:low

#380 style: update ruff version + add more rules
  .pre-commit-config.yaml
  Pipfile
  pyproject.toml
  src/metakb/__init__.py
  src/metakb/cli.py
  src/metakb/database.py
  src/metakb/harvesters/base.py
  src/metakb/harvesters/civic.py
  src/metakb/harvesters/moa.py
  src/metakb/load_data.py
  src/metakb/log_handle.py
  src/metakb/main.py
  src/metakb/normalizers.py
  src/metakb/query.py
  src/metakb/schemas/annotation.py
  src/metakb/schemas/api.py
  src/metakb/schemas/app.py
  src/metakb/schemas/categorical_variation.py
  src/metakb/schemas/variation_statement.py
  src/metakb/transform/__init__.py
  src/metakb/transform/base.py
  src/metakb/transform/civic.py
  tests/conftest.py
  tests/unit/database/test_database.py
  tests/unit/harvesters/moa/test_moa_harvest.py
  tests/unit/harvesters/moa/test_moa_source.py
  tests/unit/harvesters/test_civic_harvester.py
  tests/unit/setup/test_minimal_setup.py
  tests/unit/test_search_studies.py
  tests/unit/transform/test_civic_transform_diagnostic.py
  tests/unit/transform/test_civic_transform_prognostic.py
  tests/unit/transform/test_civic_transform_therapeutic.py
  tests/unit/transform/test_moa_transform.py
Labels: priority:low, cleanup

#384 feat: enable pagination
  pyproject.toml
  src/metakb/main.py
  src/metakb/query.py
  tests/conftest.py
  tests/unit/search/__init__.py
  tests/unit/search/test_batch_search_studies.py
  tests/unit/search/test_search_studies.py
  tests/unit/search/utils.py
Labels: priority:low

#385 chore: update seqrepo version to 2024-02-20
  .ebextensions/01_app_config.config
  docs/source/install.rst
Labels: priority:low, chore

#387 feat!: rename env var for logging + cred handling
  src/metakb/database.py
  src/metakb/log_handle.py
Labels: enhancement, priority:low

#389 build!: update ga4gh.vrs + gene/variation normalizers
  Pipfile
  pyproject.toml
  src/metakb/load_data.py
  src/metakb/main.py
  src/metakb/schemas/annotation.py
  src/metakb/schemas/categorical_variation.py
  tests/conftest.py
  tests/unit/database/test_database.py
Labels: priority:medium, build
