Repository cancervariants/metakb, pull requests merged in 2024-05, with the labels that each got.

#334 cicd: add issue templates, stalebot, and branch action
  .github/ISSUE_TEMPLATE/bug-report.yaml
  .github/ISSUE_TEMPLATE/feature-request.yaml
  .github/workflows/branch_workflow_rules.yaml
  .github/workflows/stale.yaml
Labels: priority:low, ci/cd

#332 feat!: sharpen up type usage
  .github/ISSUE_TEMPLATE/bug-report.yaml
  .github/ISSUE_TEMPLATE/feature-request.yaml
  .github/workflows/branch_workflow_rules.yaml
  .github/workflows/checks.yaml
  .github/workflows/stale.yaml
  pyproject.toml
  src/metakb/cli.py
  src/metakb/database.py
  src/metakb/harvesters/base.py
  src/metakb/harvesters/civic.py
  src/metakb/harvesters/moa.py
  src/metakb/main.py
  src/metakb/normalizers.py
  src/metakb/query.py
  src/metakb/schemas/annotation.py
  src/metakb/schemas/api.py
  src/metakb/schemas/categorical_variation.py
  src/metakb/schemas/variation_statement.py
  src/metakb/transform/base.py
  src/metakb/transform/civic.py
  src/metakb/transform/moa.py
  src/metakb/version.py
  tests/unit/database/test_database.py
  tests/unit/harvesters/moa/test_moa_assertions.py
  tests/unit/harvesters/moa/test_moa_harvest.py
  tests/unit/harvesters/moa/test_moa_source.py
  tests/unit/harvesters/test_civic_harvester.py
  tests/unit/test_search_studies.py
  tests/unit/transform/test_moa_transform.py
Labels: priority:medium

#336 feat!: create_json accepts filepath arg and only creates composite file
  src/metakb/harvesters/base.py
  src/metakb/harvesters/civic.py
  src/metakb/harvesters/moa.py
  src/metakb/transform/base.py
  tests/unit/harvesters/moa/test_moa_harvest.py
  tests/unit/harvesters/test_civic_harvester.py
  tests/unit/transform/test_civic_transform_diagnostic.py
  tests/unit/transform/test_civic_transform_prognostic.py
  tests/unit/transform/test_civic_transform_therapeutic.py
  tests/unit/transform/test_moa_transform.py
Labels: enhancement, priority:medium

#340 Revert "feat!: sharpen up type usage (#332)"
  .github/ISSUE_TEMPLATE/bug-report.yaml
  .github/ISSUE_TEMPLATE/feature-request.yaml
  .github/workflows/branch_workflow_rules.yaml
  .github/workflows/checks.yaml
  .github/workflows/stale.yaml
  pyproject.toml
  src/metakb/cli.py
  src/metakb/database.py
  src/metakb/harvesters/base.py
  src/metakb/harvesters/civic.py
  src/metakb/harvesters/moa.py
  src/metakb/main.py
  src/metakb/normalizers.py
  src/metakb/query.py
  src/metakb/schemas/annotation.py
  src/metakb/schemas/api.py
  src/metakb/schemas/categorical_variation.py
  src/metakb/schemas/variation_statement.py
  src/metakb/transform/base.py
  src/metakb/transform/civic.py
  src/metakb/transform/moa.py
  src/metakb/version.py
  tests/unit/database/test_database.py
  tests/unit/harvesters/moa/test_moa_assertions.py
  tests/unit/harvesters/moa/test_moa_harvest.py
  tests/unit/harvesters/moa/test_moa_source.py
  tests/unit/harvesters/test_civic_harvester.py
  tests/unit/test_search_studies.py
  tests/unit/transform/test_moa_transform.py
Labels: priority:high, chore

#339 feat: prevent usage of aws db instances in cli
  src/metakb/cli.py
Labels: enhancement, priority:medium

#338 refactor!: clean up harvest method
  src/metakb/cli.py
  src/metakb/harvesters/base.py
  src/metakb/harvesters/civic.py
  src/metakb/harvesters/moa.py
  tests/conftest.py
  tests/unit/harvesters/moa/test_moa_harvest.py
  tests/unit/harvesters/test_base_class.py
  tests/unit/harvesters/test_civic_harvester.py
Labels: priority:medium, technical debt

#342 feat!: sharpen type annotation
  src/metakb/cli.py
  src/metakb/database.py
  src/metakb/harvesters/base.py
  src/metakb/harvesters/civic.py
  src/metakb/harvesters/moa.py
  src/metakb/normalizers.py
  src/metakb/query.py
  src/metakb/transform/base.py
  src/metakb/transform/civic.py
  src/metakb/transform/moa.py
  tests/unit/transform/test_moa_transform.py
Labels: priority:medium

#344 feat!: break out CLI for more specific commands/more reasonable defaults
  README.md
  docs/cli/README.md
  pyproject.toml
  src/metakb/cli.py
  src/metakb/database.py
  src/metakb/normalizers.py
  src/metakb/schemas/app.py
  src/metakb/transform/base.py
Labels: priority:medium
