Repository cancervariants/metakb, pull requests merged in 2024-03, with the labels that each got.

#296 cicd: require priority label on PRs
  .github/workflows/pr-priority-label.yaml
Labels: priority:low

#300 build!: update dependencies and ga4gh digests
  Pipfile
  metakb/transform/civic.py
  metakb/transform/moa.py
  setup.cfg
  tests/conftest.py
  tests/unit/transform/test_civic_transform_therapeutic.py
  tests/unit/transform/test_moa_transform.py
Labels: priority:high, build

#306 chore: remove unused delta class
  metakb/delta.py
  tests/data/deltas/main_civic.json
  tests/data/deltas/main_moa.json
  tests/data/deltas/updated_civic.json
  tests/data/deltas/updated_moa.json
  tests/unit/deltas/test_civic_deltas.py
  tests/unit/deltas/test_moa_deltas.py
Labels: priority:low, chore

#266 feat!: update database to reflect schema changes
  Pipfile
  README.md
  metakb/database.py
  metakb/schemas/app.py
  setup.cfg
  tests/conftest.py
  tests/unit/database/test_database.py
  tests/unit/transform/test_civic_transform_therapeutic.py
Labels: enhancement, priority:medium

#307 cicd: update release.yml (publish python distribution to pypi)
  .github/workflows/release.yaml
Labels: priority:low, ci/cd

#310 fix: creating location parameterized query string
  metakb/database.py
Labels: bug, priority:medium

#279 feat!: update `/search/studies` endpoint
  metakb/main.py
  metakb/query.py
  metakb/schemas/api.py
  metakb/version.py
  tests/conftest.py
  tests/data/transform/moa_harvester.json
  tests/unit/test_query.py
  tests/unit/test_search_statements.py
  tests/unit/test_search_studies.py
  tests/unit/transform/test_moa_transform.py
Labels: enhancement, priority:medium

#280 cicd: update elastic beanstalk commands
  .ebextensions/01_app_config.config
Labels: priority:medium, ci/cd

#297 Add lab template CICD actions
  .github/workflows/checks.yaml
  .github/workflows/pr-priority-label.yaml
Labels: priority:low

#298 build: configure setuptools in pyproject.toml
  .gitignore
  Pipfile
  pyproject.toml
  setup.cfg
  setup.py
  src/metakb/__init__.py
  src/metakb/cli.py
  src/metakb/database.py
  src/metakb/exceptions.py
  src/metakb/harvesters/__init__.py
  src/metakb/harvesters/base.py
  src/metakb/harvesters/civic.py
  src/metakb/harvesters/moa.py
  src/metakb/main.py
  src/metakb/normalizers.py
  src/metakb/query.py
  src/metakb/schemas/__init__.py
  src/metakb/schemas/annotation.py
  src/metakb/schemas/api.py
  src/metakb/schemas/app.py
  src/metakb/schemas/categorical_variation.py
  src/metakb/schemas/variation_statement.py
  src/metakb/transform/README.md
  src/metakb/transform/__init__.py
  src/metakb/transform/base.py
  src/metakb/transform/civic.py
  src/metakb/transform/moa.py
  src/metakb/version.py
Labels: priority:medium

#313 style: use ruff
  .flake8
  .github/workflows/checks.yaml
  .pre-commit-config.yaml
  Pipfile
  README.md
  analysis/civic/examples/harvester/civic_harvester_example.py
  analysis/civic/examples/transform/civic_transform_example.py
  analysis/graph/db_helper.py
  analysis/moa/examples/harvester/moa_harvester_example.py
  analysis/moa/examples/transform/moa_transform_example.py
  codebuild/deploy_eb_env.py
  codebuild/deploy_eb_env_dev.py
  codebuild/terminate_eb_env.py
  codebuild/terminate_eb_env_dev.py
  pyproject.toml
  src/metakb/__init__.py
  src/metakb/cli.py
  src/metakb/database.py
  src/metakb/exceptions.py
  src/metakb/harvesters/__init__.py
  src/metakb/harvesters/base.py
  src/metakb/harvesters/civic.py
  src/metakb/harvesters/moa.py
  src/metakb/main.py
  src/metakb/normalizers.py
  src/metakb/query.py
  src/metakb/schemas/annotation.py
  src/metakb/schemas/api.py
  src/metakb/schemas/categorical_variation.py
  src/metakb/schemas/variation_statement.py
  src/metakb/transform/base.py
  src/metakb/transform/civic.py
  src/metakb/transform/moa.py
  tests/conftest.py
  tests/unit/database/test_database.py
  tests/unit/harvesters/moa/test_moa_assertions.py
  tests/unit/harvesters/moa/test_moa_harvest.py
  tests/unit/harvesters/moa/test_moa_source.py
  tests/unit/harvesters/test_base_class.py
  tests/unit/harvesters/test_civic_harvester.py
  tests/unit/setup/test_minimal_setup.py
  tests/unit/test_search_studies.py
  tests/unit/transform/test_civic_transform_diagnostic.py
  tests/unit/transform/test_civic_transform_prognostic.py
  tests/unit/transform/test_civic_transform_therapeutic.py
  tests/unit/transform/test_moa_transform.py
Labels: priority:low

#316 cicd: adjust installation checks
  .github/workflows/checks.yaml
Labels: priority:low
