Repository cancervariants/metakb, pull requests merged in 2024-06, with the labels that each got.

#346 feat: perform better logging
  src/metakb/__init__.py
  src/metakb/cli.py
  src/metakb/log_handle.py
  src/metakb/main.py
  src/metakb/transform/civic.py
Labels: priority:low

#351 build: fix pipenv build
  .github/workflows/checks.yaml
Labels: priority:high

#352 fix: use correct Disease model
  src/metakb/query.py
Labels: bug, priority:medium

#349 test: optionally minimize connection debug logging
  tests/conftest.py
Labels: priority:medium, test

#356 fix: don't use deprecated graph driver destructor
  src/metakb/cli.py
  src/metakb/main.py
  tests/unit/test_search_studies.py
Labels: priority:medium, technical debt

#358 test: remove marks from fixtures (they don't do anything)
  tests/unit/transform/test_civic_transform_diagnostic.py
  tests/unit/transform/test_civic_transform_prognostic.py
  tests/unit/transform/test_civic_transform_therapeutic.py
  tests/unit/transform/test_moa_transform.py
Labels: priority:low, test

#361 feat: add batch search by variations
  src/metakb/main.py
  src/metakb/query.py
  src/metakb/schemas/api.py
  tests/unit/test_search_studies.py
Labels: enhancement, priority:medium

#367 build: temporarily pin ga4gh.vrs==2.0.0a6
  Pipfile
  pyproject.toml
Labels: priority:high, build

#368 fix(tests): update test_batch_search to apply PR (#361) suggestions
  tests/unit/test_search_studies.py
Labels: bug, priority:low, test

#365 fix: querying studies based on therapeutic
  src/metakb/main.py
  src/metakb/query.py
  tests/unit/test_search_studies.py
Labels: bug, priority:medium
