Repository cancervariants/metakb, pull requests merged in 2025-08, with the labels that each got.

#534 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: priority:low, chore

#537 feat!: update DB connection configuration
  docs/source/config.rst
  docs/source/install.rst
  server/.env.example
  server/src/metakb/cli.py
  server/src/metakb/config.py
  server/src/metakb/database.py
  server/src/metakb/harvesters/base.py
  server/src/metakb/main.py
  server/src/metakb/transformers/base.py
Labels: priority:medium

#542 style: ignore ANN002
  server/pyproject.toml
  server/src/metakb/transformers/base.py
Labels: priority:low
