Repository cancervariants/metakb, pull requests merged in 2025-04, with the labels that each got.

#479 feat!: update models to VA-Spec 1.0.0-ballot.2025-03.4
  .gitignore
  server/Pipfile
  server/pyproject.toml
  server/src/metakb/database.py
  server/src/metakb/load_data.py
  server/src/metakb/normalizers.py
  server/src/metakb/query.py
  server/src/metakb/schemas/api.py
  server/src/metakb/transformers/base.py
  server/src/metakb/transformers/civic.py
  server/src/metakb/transformers/moa.py
  server/tests/conftest.py
  server/tests/unit/database/test_database.py
  server/tests/unit/transformers/test_civic_transformer_diagnostic.py
  server/tests/unit/transformers/test_civic_transformer_therapeutic.py
  server/tests/unit/transformers/test_moa_transformer_prognostic.py
  server/tests/unit/transformers/test_moa_transformer_therapeutic.py
Labels: enhancement, priority:high, stale

#473 cicd: update ruff, precommit
  .github/workflows/checks.yaml
  .gitignore
  .pre-commit-config.yaml
  client/public/vite.svg
  client/src/assets/react.svg
  docs/make.bat
  docs/source/conf.py
  docs/source/reference/api/metakb.harvesters.base.rst
  docs/source/reference/api/metakb.harvesters.civic.rst
  docs/source/reference/api/metakb.harvesters.moa.rst
  docs/source/reference/api/metakb.normalizers.rst
  docs/source/reference/api/metakb.query.rst
  docs/source/reference/api/metakb.schemas.api.rst
  docs/source/reference/api/metakb.schemas.app.rst
  package.json
  server/.ebextensions/00_metakb_log.config
  server/pyproject.toml
  server/src/metakb/cli.py
  server/src/metakb/database.py
  server/src/metakb/harvesters/base.py
  server/src/metakb/load_data.py
  server/src/metakb/normalizers.py
  server/src/metakb/query.py
  server/tests/conftest.py
  server/tests/data/harvesters/moa/variants.json
  server/tests/unit/transformers/test_moa_transformer_therapeutic.py
Labels: priority:low

#485 fix(ci): fix deployment, remove pipfile + update seqrepo version
  .ebextensions/00_app_log.config
  .ebextensions/01_build.config
  .ebextensions/02_data_downloads.config
  .github/workflows/checks.yaml
  Procfile
  README.md
  docs/source/contributing.rst
  docs/source/install.rst
  requirements.txt
  server/Pipfile
  server/Procfile
Labels: bug, priority:high, ci/cd
